### ISSUE TITLE
解析出错了

### ISSUE THREAD

**Issue by plmxs2017** [nilaoda/ViuParser#1]
![Snipaste_2019-08-22_07-53-06](https://user-images.githubusercontent.com/44402965/63476124-56250400-c4b2-11e9-9dea-015cda104749.png)
解析出错了

**Comment by nilaoda** [comment]
等有空再看看

**Comment by a88wyzz** [comment]
首先感谢大佬写这个程序，目前是错误状态，不知道此程序能不能些加入一些小选项，比如BAT、字幕默认下载到当前目录或者下载到指定的目录，不要每次都要选择下载目录，还有填写代理IP的选项，再次感谢大佬~！

**Comment by YFTX2015** [comment]
我用这个也是一样的情况。替代方法是用火狐插件flash video downloader获取会员清晰度视频m3u8链接，然后再配合m3u8 downloader下载，VTT字幕用idm可以获取。本来这个插件自带下载功能，但是要配合合作应用组件一起使用才行，但是现在软件更新后附加组件却并未更新，所以现在下载按钮失效，但是可以用它旁边的复制按钮获取m3u8链接。
